image: curlimages/curl:latest


stages:
  - upload

upload:
  tags:
    - siesta
    - shell
    - fast
  stage: upload
  script:
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file docker-image/inspec.yml "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/my_package/0.0.1/file.txt"'
